#!/bin/bash

RELX_RIAK={{platform_bin_dir}}/riak

export RELX_OUT_FILE_PATH={{platform_gen_dir}}
if [ -r $RELX_OUT_FILE_PATH/vm.args ]; then
    export VMARGS_PATH={{platform_gen_dir}}/vm.args
fi

export PID_DIR={{pid_dir}}

mkdir -p $PID_DIR

case "$1" in
    start)
        $RELX_RIAK $* -pa {{platform_patch_dir}}
        test -r $PID_DIR/riak.pid && exit 0
        ;;
    console|foreground)
        $RELX_RIAK $* -pa {{platform_patch_dir}}
        ;;
    stop)
        $RELX_RIAK $* \
            && rm -f $PID_DIR/riak.pid
        ;;
    *)
        ESCAPED_ARGS=`echo "$@" | sed -e 's/\([\\\(\\\){}"\x27]\)/\\\\\1/g'`
        $RELX_RIAK $ESCAPED_ARGS
        ;;
esac
