#!/bin/bash

RUNNER_GEN_DIR={{platform_gen_dir}}
RELX_RIAK={{platform_bin_dir}}/riak
export PID_DIR={{pid_dir}}

mkdir -p $PID_DIR

case "$1" in
    stop)
        $RELX_RIAK $* \
            && rm -f $PID_DIR/riak.pid
        ;;
    *)
        $RELX_RIAK $*
        ;;
esac
