#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

PLATFORM_BASE_DIR={{platform_base_dir}}
PLATFORM_BASE_DIR=${PLATFORM_BASE_DIR:-$(cd $(dirname "$0")/.. && pwd -P)}
RELEASE_ROOT_DIR=$PLATFORM_BASE_DIR

PLATFORM_ETC_DIR={{platform_etc_dir}}
if [ "$PLATFORM_ETC_DIR" = "${PLATFORM_ETC_DIR#/}" ]; then
    PLATFORM_ETC_DIR=$PLATFORM_BASE_DIR/$PLATFORM_ETC_DIR
fi

RUNNER_GEN_DIR={{platform_gen_dir}}
RUNNER_ETC_DIR=$PLATFORM_ETC_DIR

ERTS_VER=$(cd ${PLATFORM_BASE_DIR} && ls -d erts-*)
ERTS_PATH="${PLATFORM_BASE_DIR}/$ERTS_VER/bin"
ERTS_DIR=$ERTS_PATH/..
COOKIE=`egrep '^[ \t]*distributed_cookie[ \t]*=[ \t]*' $PLATFORM_ETC_DIR/riak.conf 2> /dev/null | cut -d = -f 2 | tr -d ' '`

NODE=`egrep '^[ \t]*nodename[ \t]*=[ \t]*' $PLATFORM_ETC_DIR/riak.conf 2> /dev/null | cut -d = -f 2 | tr -d ' '`
HOST=${NODE#*@}

BOOT_FILE="${PLATFORM_BASE_DIR}/releases/{{release_version}}/start_clean"

. $PLATFORM_BASE_DIR/bin/cf_config

BOOT_FILE="${PLATFORM_BASE_DIR}/releases/{{release_version}}/start_clean"

CODE=" try
           {ok, _} = file:consult(\"$CONFIG_PATH\"),
           io:format(\"config is OK\\n\"),
           halt(0)
       catch
           _:_ ->
               io:format(\"Error reading ~p\\n\", [\"$CONFIG_PATH\"]),
               halt(1)
       end."

$ERTS_DIR/bin/erl -noshell -noinput \
                  -boot $BOOT_FILE \
                  -eval "$CODE"

echo $CUTTLE_CONF
