#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

ERTS_PATH="{{runner_base_dir}}/`(cd {{runner_base_dir}} && ls -d erts-*)`/bin"
COOKIE=`egrep '^[ \t]*distributed_cookie[ \t]*=[ \t]*' {{platform_etc_dir}}/riak.conf 2> /dev/null | cut -d = -f 2 | tr -d ' '`
NODE={{node}}
HOST=${NODE#*@}

BOOT_FILE="{{runner_base_dir}}/releases/{{release_version}}/start_clean"

CONFIG_PATH=`ls -1r {{platform_gen_dir}}/generated.conf/app.*.config | head -n1`
VMARGS_PATH=`ls -1r {{platform_gen_dir}}/generated.conf/vm.*.args | head -n1`

CODE=" try
           {ok, _} = file:consult(\"$CONFIG_PATH\"),
           io:format(\"config is OK\\n\"),
           halt(0)
       catch
           _:_ ->
               io:format(\"Error reading ~p\\n\", [\"$CONFIG_PATH\"]),
               halt(1)
       end."

$ERTS_PATH/erl -noshell -noinput \
               -pa {{runner_base_dir}} \
               -boot $BOOT_FILE \
               -hidden -name riak_chkconfig$RAND@$HOST -setcookie $COOKIE \
               -node $NODE  -tracing off \
               -eval "$CODE"

echo $CONFIG_PATH $VMARGS_PATH
